import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createGuildAction, joinGuildAction, leaveGuildAction } from "./actions";
import { MoriseNavigation, SocialQuickNav } from "@/components/morise-navigation";
import "./guilds.css";

export default async function GuildsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth/sign-in");
  const { data: guilds } = await supabase.from("social_groups").select("id, name, description, visibility, owner_id, created_at, social_group_members(player_id, role)").order("created_at", { ascending: false }).limit(60);
  const cards = (guilds ?? []).map((guild) => { const members = (guild.social_group_members ?? []) as Array<{ player_id: string; role: string }>; return { ...guild, memberCount: members.length, membership: members.find((member) => member.player_id === user.id) }; });
  return <main className="guilds-main"><section className="guilds-shell"><MoriseNavigation /><SocialQuickNav mode="guilds" /><header className="guilds-header"><div><p className="guilds-kicker">SOCIAL / COLLECTIVE</p><h1>GUILDS</h1><p>Find your people, build a space, and turn shared interests into shared play.</p></div><Link href="/social" className="guilds-back">← SOCIAL</Link></header><section className="guild-create"><div><span className="guilds-index">01 / CREATE</span><h2>Build a Guild</h2><p>Start small. The SYSTEM can grow the space with you.</p></div><form action={createGuildAction} className="guild-create-form"><label>Name<input name="name" required maxLength={80} placeholder="e.g. Shonen Vanguard" /></label><label>Description<textarea name="description" maxLength={1000} placeholder="What is this guild about?" /></label><label>Visibility<select name="visibility" defaultValue="public"><option value="public">Public — anyone can join</option><option value="private">Private — invitation only</option></select></label><button type="submit">Create Guild</button></form></section><section className="guild-list"><div className="guilds-section-heading"><div><span className="guilds-index">02 / DISCOVER</span><h2>Guilds around the World</h2></div><span>{cards.length} visible</span></div>{cards.length === 0 ? <div className="guild-empty"><strong>No guilds yet.</strong><p>Create the first one and give the World somewhere to gather.</p></div> : <div className="guild-grid">{cards.map((guild) => <article className="guild-card" key={guild.id}><div className="guild-card-top"><span className="guild-badge">{guild.visibility === "private" ? "PRIVATE" : "PUBLIC"}</span><span>{guild.memberCount} member{guild.memberCount === 1 ? "" : "s"}</span></div><h3>{guild.name}</h3><p>{guild.description || "An open space for Otaku interests."}</p><div className="guild-card-actions">{guild.membership ? guild.membership.role === "owner" ? <span className="guild-owner">OWNER</span> : <form action={leaveGuildAction}><input type="hidden" name="group_id" value={guild.id} /><button type="submit" className="guild-secondary">Leave</button></form> : guild.visibility === "public" ? <form action={joinGuildAction}><input type="hidden" name="group_id" value={guild.id} /><button type="submit">Join Guild</button></form> : <span className="guild-private-note">Invitation required</span>}</div></article>)}</div>}</section></section></main>;
}
